### ISSUE TITLE
HIST_FIND_NO_DUPS causes most recent match to be skipped the second time around

### ISSUE THREAD

**Issue by sampsyo** [zsh-users/zsh-history-substring-search#46] opened 2015-10-26 21:47 UTC
When I enable the `HIST_FIND_NO_DUPS` option (see #19), if I first use the plugin to find the most recent match, *subsequent* invocations of the plugin find me the second-most-recent match first.

For example, enter these commands:

```
$ foo 1
$ foo 2
```

Then, typing `foo<up>` (with the ordinary bindings) at first correctly gives the completions in this order:

1. `foo 2`
2. `foo 1`

However, if you accept the first completion, `foo 2`, then invoke the plugin *again* by typing `foo<up>`, it skips directly to `foo 1`.

**Comment by sunaku** [comment] 2015-10-26 21:59
I couldn't reproduce the problem here (using `echo` instead of `foo`) under zsh 5.1.1. :disappointed_relieved:

**Comment by sampsyo** [comment] 2015-10-26 22:03
Oh dear. Thanks for looking. I'm also on 5.1.1, on Arch Linux. I'll try narrowing it down to see if something else is interfering.

**Comment by sunaku** [comment] 2015-11-15 21:38
Alright, closing. :cop: Please reopen/comment if you have new information.

**Closed by sunaku** 2015-11-15 21:38 UTC
