### ISSUE TITLE
up down functions stopped working after update

### ISSUE THREAD

**Issue by l3pp4rd** [zsh-users/zsh-history-substring-search#50] opened 2015-12-15 19:27 UTC
![2015-12-15-212437_](https://cloud.githubusercontent.com/assets/132389/11821492/7b992e1a-a372-11e5-93bb-6c44e75ed061.png)

seems like the [following change](https://github.com/zsh-users/zsh-history-substring-search/commit/e2ab5b8214c50c2cb39d370fe4863576fd3eeffe) introduced it

**Comment by yepengfan** [comment] 2016-01-21 00:13
Got the same issue. After updated today.

**Comment by sunaku** [comment] 2016-01-21 00:36
Sorry, I'm not able to reproduce the issue under a minimal (`zsh -f`) ZSH session: :disappointed_relieved:

![zsh-history-substring-search-up](https://cloud.githubusercontent.com/assets/9863/12467865/de30471a-bf93-11e5-9db6-6274a25ca6ad.png)

**Comment by yepengfan** [comment] 2016-01-21 01:20
autosuggest-restore-widgets:zle:3: no such widget `.history-substring-search-up'
autosuggest-restore-widgets:zle:3: no such widget `.history-substring-search-down'

Hi @sunaku this is the message I have got. I just update the plugin this morning using antigen. After that, every time I start a new terminal session / window, I will get these messages. 

Hope it help! Cheers.

**Comment by sunaku** [comment] 2016-01-21 02:26
Sorry, but I cannot help with your issue because it is caused by something that is _outside_ of this plugin: notice how I couldn't reproduce the issue under a minimal `zsh -f` session in my previous response. :sweat_smile:

You may want to ask Antigen developers for help instead. :dart:  I'm closing this issue here: it's not a bug. :cop:

**Closed by sunaku** 2016-01-21 02:26 UTC

**Comment by l3pp4rd** [comment] 2016-01-21 08:09
well, if it is not related fine. I will update if I'll go into debugging, so far I'm using an older version. my stack is with oh-my-zsh, probably one of the other plugins has a conflict

**Comment by z0rc** [comment] 2016-01-21 11:08
Caused by zsh-autosuggestions plugin, see https://github.com/tarruda/zsh-autosuggestions/issues/88.

**Comment by l3pp4rd** [comment] 2016-01-21 11:10
indeed @z0rc thanks for the reference ;)

**Comment by l3pp4rd** [comment] 2016-01-21 11:54
ah in my case it is because of keybindings

``` zsh
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
```
